'use client';
import {useEffect,useRef,useState} from 'react';
import {Fuel,Car,ScanLine,ShieldCheck,ArrowRight,ArrowLeft,History,CheckCircle2,Wifi,WifiOff,RotateCcw,HelpCircle,LogOut,ReceiptText} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {copy,Key} from '@/lib/copy';
import {initialState,remaining,vehicles,dispense,validate,isDemoState,DemoState,Transaction} from '@/lib/demo';
const STORAGE='group-c-fuel-demo-v1';
export default function Home(){
 const [lang,setLang]=useState<'en'|'si'|'ta'>('en');const t=(key:Key)=>copy[lang][key];
 const [role,setRole]=useState('motorist'),[view,setView]=useState('overview'),[signed,setSigned]=useState(false),[otp,setOtp]=useState(''),[expiry,setExpiry]=useState(0),[error,setError]=useState<Key|null>(null),[notice,setNotice]=useState<Key|null>(null);
 const [state,setState]=useState<DemoState>(initialState),[ready,setReady]=useState(false),[persist,setPersist]=useState(true);const ref=useRef(state);
 const [vehicle,setVehicle]=useState(vehicles[0].id),[pass,setPass]=useState(''),[step,setStep]=useState('scan'),[litres,setLitres]=useState(''),[online,setOnline]=useState(true),[receipt,setReceipt]=useState<Transaction|null>(null),[help,setHelp]=useState(false),[station,setStation]=useState('all'),[detail,setDetail]=useState<Transaction|null>(null);const txId=useRef('');const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const parsed=JSON.parse(raw);if(isDemoState(parsed)){setState(parsed);ref.current=parsed;}}}catch{setPersist(false)}setReady(true);setExpiry(Date.now()+120000)},[]);
 useEffect(()=>{if(ready){ref.current=state;try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{setPersist(false)}}},[state,ready]);
 useEffect(()=>{document.documentElement.lang=lang},[lang]);
 useEffect(()=>{heading.current?.focus({preventScroll:true})},[view,step,role,signed]);
 const v=vehicles.find(v=>v.id===vehicle)!;const found=vehicles.find(v=>v.pass===pass.trim().toUpperCase());const balance=remaining(state,v);
 const changeRole=(r:string)=>{setRole(r);setError(null);setNotice(null);setDetail(null)};
 const begin=(p:string)=>{setError(null);if(!online){setError('offline');return}if(!vehicles.some(v=>v.pass===p.trim().toUpperCase())){setError('unknown');return}setPass(p.trim().toUpperCase());setStep('litres');setLitres('');txId.current=`TX-${String(ref.current.transactions.length+1).padStart(3,'0')}`};
 const commit=()=>{const result=dispense(ref.current,pass,litres,txId.current,online);if(result.error){setError(result.error as Key);return}ref.current=result.state;setState(result.state);setReceipt(result.transaction!);setStep('receipt');setError(null)};
 const reset=()=>{const fresh=initialState();ref.current=fresh;setState(fresh);setStep('scan');setPass('');setLitres('');setReceipt(null);setDetail(null);setView('overview');setVehicle(vehicles[0].id);setSigned(false);setOtp('');setExpiry(Date.now()+120000);setOnline(true);setError(null);setNotice('saved')};
 const title=role==='admin'?t('operations'):role==='attendant'?t(step==='receipt'?'success':step==='review'?'reviewTitle':'scanTitle'):!signed?t('signIn'):t(view==='pass'?'passTitle':view==='history'?'history':'dashboard');
 const history=(items:Transaction[])=>items.length?<div className="transaction-list">{[...items].reverse().map(tr=><div className="transaction" key={tr.id}><span className="transaction-icon"><Fuel size={20}/></span><div><strong>{tr.station}</strong><p>{tr.id} · {tr.time.slice(0,10)}</p></div><strong className="amount">−{tr.litres.toFixed(2)} L</strong></div>)}</div>:<div className="empty"><History size={36}/><h3>{t('empty')}</h3><p>{t('emptyHelp')}</p></div>;
 return <><a className="skip" href="#main">Skip to content</a><div className="proposal-bar"><span>Proposal prototype</span><span>Demo data · Group C</span></div><header className="site-header"><a href="/" className="brand" aria-label="Fuel Pass home"><span className="brand-icon"><Fuel/></span><span>Fuel<span className="brand-accent">Pass</span><small>SRI LANKA · DESIGN PROPOSAL</small></span></a><label className="language"><span className="sr-only">Language</span><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as typeof lang)}><option value="en">English</option><option value="si">සිංහල</option><option value="ta">தமிழ்</option></select></label></header>
 <div className="workspace"><aside className="rail"><p className="eyebrow">{t('role')}</p><Tabs value={role} onValueChange={changeRole} orientation="vertical"><TabsList className="role-tabs"><TabsTrigger value="motorist"><Car/>{t('motorist')}</TabsTrigger><TabsTrigger value="attendant"><ScanLine/>{t('attendant')}</TabsTrigger><TabsTrigger value="admin"><ShieldCheck/>{t('admin')}</TabsTrigger></TabsList></Tabs><div className="rail-bottom"><div className="network">{online?<Wifi size={18}/>:<WifiOff size={18}/>}<div>{t('network')}<strong>{t(online?'connected':'disconnected')}</strong></div></div><Button variant="ghost" onClick={()=>setHelp(!help)} aria-expanded={help}><HelpCircle/>{t('help')}</Button>{signed&&<Button variant="ghost" onClick={()=>{setSigned(false);setView('overview');setOtp('');setNotice('signedOut')}}><LogOut/>{t('signOut')}</Button>}</div></aside>
 <main id="main" className="main"><div className="page-heading"><div><p className="eyebrow">{role==='admin'?t('sample'):role==='attendant'?'DEMO-ST-01':t('welcome')}</p><h1 tabIndex={-1} ref={heading}>{title}</h1></div><span className="demo-badge">DEMO</span></div>
 {notice&&<div className="message success" role="status">{t(notice)}</div>}{error&&<div className="message error" role="alert">{t(error)}</div>}{!persist&&<div className="message">Browser storage is unavailable. Changes last only while this page stays open.</div>}
 {help&&<section className="card help-card"><h2>{t('help')}</h2><p>{t('helpText')}</p><div className="switch-row"><Switch id="offline" checked={!online} onCheckedChange={x=>setOnline(!x)}/><label htmlFor="offline">{t('offlineToggle')}</label></div><div className="actions"><Button variant="outline" onClick={reset}><RotateCcw/>{t('reset')}</Button><Button variant="outline" onClick={()=>{setExpiry(0);setError(null)}}>{t('expire')}</Button></div><h3>{t('register')}</h3><p>{t('registerText')}</p></section>}
 {role==='motorist'&&!signed&&<div className="login-grid"><section className="card login-card"><span className="large-icon"><ShieldCheck size={30}/></span><h2>{t('signIn')}</h2><p>{t('otpHelp')}</p><form onSubmit={e=>{e.preventDefault();setNotice(null);if(!online){setError('offline');return}if(Date.now()>expiry){setError('expired');return}if(otp!=='123456'){setError('invalidOtp');return}setSigned(true);setError(null)}}><label htmlFor="otp">{t('code')}</label><input id="otp" inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value)} placeholder="123456" aria-invalid={error==='invalidOtp'||error==='expired'}/><Button className="full" type="submit">{t('verify')}<ArrowRight/></Button></form><Button variant="ghost" onClick={()=>{if(!online){setError('offline');return}setExpiry(Date.now()+120000);setOtp('');setError(null);setNotice(null)}}>{t('resend')}</Button></section><section className="intro-panel"><span className="eyebrow">ONE CONNECTED DEMO</span><h2>Your pass.<br/>A clearer journey.</h2><p>See your allowance. Show your pass. Know what was recorded.</p><div className="intro-step"><span>01</span><p>Motorist<br/><strong>Check & present your pass</strong></p></div><div className="intro-step"><span>02</span><p>Station attendant<br/><strong>Validate & record dispensing</strong></p></div><div className="intro-step"><span>03</span><p>Administrator<br/><strong>Inspect activity & audit records</strong></p></div></section></div>}
 {role==='motorist'&&signed&&<><div className="vehicle-row"><label htmlFor="vehicle">{t('select')}</label><select id="vehicle" value={vehicle} onChange={e=>{setVehicle(e.target.value);setView('overview')}}>{vehicles.map(v=><option key={v.id}>{v.id}</option>)}</select></div>{view==='overview'?<div className="dashboard-grid"><section className="allowance-card"><div className="card-top"><span>{t('remaining')}</span><Car/></div><p className="balance">{balance.toFixed(2)}<span>L</span></p><div className="meter" role="meter" aria-label={t('remaining')} aria-valuenow={balance} aria-valuemin={0} aria-valuemax={v.allocation}><span style={{width:`${balance/v.allocation*100}%`}}/></div><div className="allowance-meta"><span>{t('used')}<strong>{(v.allocation-balance).toFixed(2)} L</strong></span><span>{t('allocation')}<strong>{v.allocation.toFixed(2)} L</strong></span></div><Button className="pass-button full" onClick={()=>setView('pass')}><ScanLine/>{t('openPass')}<ArrowRight/></Button><p className="allowance-note">{t('noReal')}</p></section><section className="card"><div className="card-top"><h2>{t('recent')}</h2><History size={20}/></div>{history(state.transactions.filter(tr=>tr.vehicle===v.id).slice(-3))}<Button variant="outline" className="full" onClick={()=>setView('history')}>{t('history')}<ArrowRight/></Button></section></div>:view==='pass'?<section className="card pass-card"><span className="tag">{v.id}</span><h2>{t('passTitle')}</h2><img className="qr" src={v.pass==='DEMO-PASS-001'?'/qr-001.svg':'/qr-002.svg'} alt={`Demo QR code for ${v.pass}`}/><code className="pass-code">{v.pass}</code><p>{t('passHelp')}</p><div className="pass-balance">{t('remaining')} <strong>{balance.toFixed(2)} L</strong></div><Button variant="outline" onClick={()=>setView('overview')}><ArrowLeft/>{t('back')}</Button></section>:<section className="card">{history(state.transactions.filter(tr=>tr.vehicle===v.id))}<Button variant="outline" onClick={()=>setView('overview')}><ArrowLeft/>{t('back')}</Button></section>}</>}
 {role==='attendant'&&<div className="attendant-grid"><section className="card attendant-card">{step==='scan'?<><div className="scanner-box"><ScanLine size={64}/><p>{t('scanHelp')}</p><Button onClick={()=>begin('DEMO-PASS-001')}>{t('scan')}</Button></div><form onSubmit={e=>{e.preventDefault();begin(pass)}}><label htmlFor="pass">{t('passCode')}</label><input id="pass" value={pass} onChange={e=>setPass(e.target.value)} placeholder="DEMO-PASS-001"/><Button variant="outline" className="full" type="submit">{t('validate')}<ArrowRight/></Button></form></>:step==='receipt'&&receipt?<><div className="success-symbol"><CheckCircle2 size={48}/></div><h2>{t('success')}</h2><p>{t('receipt')} · {receipt.id}</p><dl><div><dt>{t('vehicle')}</dt><dd>{receipt.vehicle}</dd></div><div><dt>{t('litres')}</dt><dd>{receipt.litres.toFixed(2)} L</dd></div><div><dt>{t('station')}</dt><dd>{receipt.station}</dd></div><div><dt>{t('after')}</dt><dd>{remaining(state,vehicles.find(v=>v.id===receipt.vehicle)!).toFixed(2)} L</dd></div></dl><Button className="full" onClick={()=>{setStep('scan');setError(null);setPass('');setReceipt(null)}}>{t('another')}</Button><Button variant="ghost" className="full" onClick={commit}>{t('retryDuplicate')}</Button></>:found?<><span className="tag"><CheckCircle2 size={16}/>{t('eligible')}</span><h2>{found.id}</h2><div className="available"><span>{t('remaining')}</span><strong>{remaining(state,found).toFixed(2)} L</strong></div>{step==='litres'?<form onSubmit={e=>{e.preventDefault();const err=validate(ref.current,pass,litres,online);setError(err as Key|null);if(!err)setStep('review')}}><label htmlFor="litres">{t('litres')}</label><input id="litres" inputMode="decimal" value={litres} onChange={e=>setLitres(e.target.value)} placeholder="5.00"/><Button className="full" type="submit">{t('review')}<ArrowRight/></Button><Button type="button" variant="ghost" onClick={()=>{setStep('scan');setError(null)}}>{t('passCode')}</Button></form>:<><dl><div><dt>{t('litres')}</dt><dd>{Number(litres).toFixed(2)} L</dd></div><div><dt>{t('after')}</dt><dd>{(remaining(state,found)-Number(litres)).toFixed(2)} L</dd></div></dl><p>{t('confirmHelp')}</p><Button className="full" onClick={commit}>{t('confirm')}</Button><Button className="full" variant="ghost" onClick={()=>{setStep('litres');setError(null)}}>{t('edit')}</Button></>}</>:null}</section><aside className="card supporting"><p className="eyebrow">{t('station')}</p><h2>DEMO-ST-01</h2><p>{t('sample')}</p><hr/><ReceiptText size={28}/><h3>One record, three views</h3><p>Every confirmed demo transaction updates the motorist’s balance, transaction history and administrative activity in this browser.</p><p className="small">No real fuel is dispensed. No official systems are connected.</p></aside></div>}
 {role==='admin'&&<><div className="stats">{[[t('total'),`${state.transactions.reduce((n,tr)=>n+tr.litres,0).toFixed(2)} L`],[t('transactions'),state.transactions.length],[t('flags'),state.transactions.filter(tr=>tr.flagged).length]].map(([label,value])=><section className="card stat" key={label}><p>{label}</p><strong>{value}</strong><span>{t('sample')}</span></section>)}</div><section className="card"><div className="card-top"><h2>{t('activity')}</h2><select aria-label={t('station')} value={station} onChange={e=>setStation(e.target.value)}><option value="all">{t('all')}</option><option>DEMO-ST-01</option><option>DEMO-ST-02</option></select></div><div className="table-wrap"><table><thead><tr><th>{t('receipt')}</th><th>{t('vehicle')}</th><th>{t('station')}</th><th>{t('litres')}</th><th>{t('inspect')}</th></tr></thead><tbody>{[...state.transactions].reverse().filter(tr=>station==='all'||tr.station===station).map(tr=><tr key={tr.id}><td>{tr.id}{tr.flagged&&<span className="flag-label">{t('flags')}</span>}</td><td>{tr.vehicle}</td><td>{tr.station}</td><td>{tr.litres.toFixed(2)} L</td><td><Button variant="outline" onClick={()=>setDetail(tr)} aria-label={`${t('inspect')} ${tr.id}`}>{t('inspect')}</Button></td></tr>)}</tbody></table></div></section>{detail&&<section className="card audit" aria-live="polite"><div className="card-top"><h2>{t('audit')} · {detail.id}</h2><Button variant="ghost" onClick={()=>setDetail(null)}>{t('close')}</Button></div>{detail.flagged&&<p className="message">{t('flagHelp')}</p>}<ol><li>Demo pass matched: {detail.vehicle}</li><li>Illustrative allowance checked</li><li>{detail.litres.toFixed(2)} L recorded at {detail.station}</li><li>Receipt {detail.id} created · {detail.time}</li></ol><p className="small">Reconstructed demo events, not a tamper-resistant audit log.</p></section>}</>}
 <footer><p>{t('about')}</p><p>{t('draft')}</p><Button variant="ghost" onClick={reset}><RotateCcw size={16}/>{t('reset')}</Button></footer></main></div></>;
}
