export type Vehicle={id:string;pass:string;allocation:number};
export type Transaction={id:string;vehicle:string;litres:number;time:string;station:string;flagged?:boolean};
export type DemoState={version:1;transactions:Transaction[]};
export const vehicles:Vehicle[]=[{id:'DEMO-CAR-01',pass:'DEMO-PASS-001',allocation:30},{id:'DEMO-BIKE-02',pass:'DEMO-PASS-002',allocation:5}];
export const initialState=():DemoState=>({version:1,transactions:[{id:'TX-001',vehicle:'DEMO-CAR-01',litres:7,time:'2026-09-10T09:00:00Z',station:'DEMO-ST-01'},{id:'TX-002',vehicle:'DEMO-CAR-01',litres:5,time:'2026-09-11T10:30:00Z',station:'DEMO-ST-02',flagged:true}]});
export const remaining=(s:DemoState,v:Vehicle)=>Math.round((v.allocation-s.transactions.filter(t=>t.vehicle===v.id).reduce((n,t)=>n+t.litres,0))*100)/100;
export function validate(s:DemoState,pass:string,input:string,online=true):string|null {if(!online)return 'offline';const v=vehicles.find(v=>v.pass===pass.trim().toUpperCase());if(!v)return 'unknown';if(!/^\d+(\.\d{1,2})?$/.test(input)||Number(input)<=0)return 'invalidLitres';if(Number(input)>remaining(s,v))return 'insufficient';return null;}
export function dispense(s:DemoState,pass:string,input:string,id:string,online=true):{state:DemoState;error:string|null;transaction?:Transaction}{if(s.transactions.some(t=>t.id===id))return {state:s,error:'duplicate'};const error=validate(s,pass,input,online);if(error)return {state:s,error};const v=vehicles.find(v=>v.pass===pass.trim().toUpperCase())!;const transaction={id,vehicle:v.id,litres:Number(input),time:new Date(Date.UTC(2026,8,13,9,0,s.transactions.length)).toISOString(),station:'DEMO-ST-01'};return {state:{version:1,transactions:[...s.transactions,transaction]},error:null,transaction};}
export function isDemoState(s:unknown):s is DemoState {if(!s||typeof s!=='object')return false;const d=s as DemoState;return d.version===1&&Array.isArray(d.transactions)&&d.transactions.every(t=>typeof t.id==='string'&&vehicles.some(v=>v.id===t.vehicle)&&Number.isFinite(t.litres)&&t.litres>0&&typeof t.time==='string'&&typeof t.station==='string')&&new Set(d.transactions.map(t=>t.id)).size===d.transactions.length&&vehicles.every(v=>remaining(d,v)>=0);}
